apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: marinastancu/accounts:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: Auth0__Domain
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: DOMAIN
            - name: Auth0__ManagementApiAccessToken
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: TOKEN
            - name: ASPNETCORE_ENVIRONMENT
              value: "Release"
            - name: RabbitMQ__HostName
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: HOST
            - name: RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: PORT
            - name: RabbitMQ__UserName
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: USER
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: PASSWORD
            - name: RabbitMQ__QueueName__Data
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: EVENTS_QUEUE
            - name: RabbitMQ__QueueName__Deletion
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: DELETION_QUEUE
            - name: MongoDB__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: CONNECTION_STRING
            - name: MongoDB__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: NAME
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 5001